### ISSUE TITLE
License for images?

### ISSUE THREAD

**Issue by davidlmobley** [pele-python/pele#165]
I'm looking for an example disconnectivity graph I can show in a class (and make available in the course materials on GitHub for free). You have a perfect one in your docs (an LJ 36 cluster I believe) and I'd love to be able to show it, but the licensing terms are not clear (the code is GPL but the non-code content isn't under a license I see). Any chance you're willing to put clear reuse terms on those? e.g. CC-BY or CC-BY-SA or similar? 

(I basically just want to be able to show your image, say whose image it was, explain what it shows, and link back to where it came from, e.g. in my github.com/mobleylab/drug-computing course materials).

**Comment by js850** [comment]
Hi.  That would be fine.  I'm no licence expert, if you tell me what to do I can do it.  e.g. a file in the doc directory.  Even better you could make a pull request and I'll merge it.

p.s. there are some good disconnectivity graph images here also http://www-wales.ch.cam.ac.uk/~wales/

**Comment by davidlmobley** [comment]
Pretty booked today so I can't do a PR right now, but check out https://github.com/MobleyLab/drug-computing/blob/master/LICENSE for a CC-BY license; the way I've dealt with this is I just put two license files in my main folder -- one a license for code and one a license for the non-code content. So in your case you might have your current LICENSE file which is GPL, and then a "LICENSE_content" file which is CC-BY. (This would make all of the non-code content in your repo be available under CC-BY, or whatever license you choose. If you prefer to restrict this to only a subset then you'd need to adjust your organization accordingly.)

You can pull the license of your choice from https://creativecommons.org/licenses/

If you want to learn a little more about licensing and why you should care, I recommend Stodden's work on the topic (e.g. see http://aip.scitation.org/doi/abs/10.1109/MCSE.2009.19 ). 

(Tangentially related set of remarks: A lot of academics tend to like GPL for code, but I'm basically with Stodden -- better is MIT or BSD because GPL is "infectious". There's a big reason why a lot of the packages we know/love/use a ton (numpy, scipy, scikit-learn, etc.) have gone with MIT or BSD-3: It allows the broadest audience to be able to use them for any purpose whatsoever and gives them incentive to contribute back. GPL can be problematic because commercial companies are disincentivized from contributing to it since then it means they can't use the code (even their own contributions to it) in their own commercial work/code without then having to give away all of their commercial code for free. Because I collaborate with for-profit companies I basically can't use anything GPL-based in any of my work because my collaborators then wouldn't be able to use it for fear it would contaminate their code when they use my code.)

I do know Wales's work. The thing that actually started me on this quest was that I wanted to use a disconnectivity graph from one of his papers but of course the journal's copyright doesn't allow it, so I started hunting for a disconnectivity graph which was licensed for reuse.
