### ISSUE TITLE
Error with GUI

### ISSUE THREAD

**Issue by WCEdison** [pele-python/pele#168]
When running the pele_gui, there has been an error where the config_parser cannot be found in the local installation. This has never happened before and I have also tested using the example scripts in example folder

wcedison@wcedison-VirtualBox:~/Downloads/pele-master/examples/gui$ python ljsystem.py 
\Traceback (most recent call last):
  File "ljsystem.py", line 6, in <module>
    from pele.gui import run_gui
  File "/home/wcedison/.local/lib/python2.7/site-packages/pele/gui/__init__.py", line 46, in <module>
    from .run import run_gui
  File "/home/wcedison/.local/lib/python2.7/site-packages/pele/gui/run.py", line 14, in <module>
    from pele.config import config
  File "/home/wcedison/.local/lib/python2.7/site-packages/pele/config.py", line 2, in <module>
    import configparser
ImportError: No module named configparser

**Comment by WCEdison** [comment]
Solution Found: this is because of a incompatibility between python 3 and python 2, while the system is compatible with both, should a configpaser be called from python2.8/2.7, the actual name should be ConfigParser instead of configparser (case sensitive), all user that have default installed at python 2 will have to go to the sources code and use sudo gedit for properly result (change the line import configparser to ConfigParser, and also the following lines.)

**Comment by js850** [comment]
Hi @WCEdison, good find.  Is this something that can be fixed in the code?  If so, a pull request would be most welcome!

**Comment by WCEdison** [comment]
@js850  I have fixed the problem locally by manually converting config.py to python 2-3 compatible script 
https://docs.python.org/2/library/configparser.html The reference of my change is listed in official python configparser document.
My change also apply the sample code provided from the follow python 2-3 compatibility site, which I have tested it successfully locally (with GUI and basinhopping)
https://python-future.org/compatible_idioms.html

from __future__ import print_function
from configparser import ConfigParser
from os.path import expanduser

config = ConfigParser.ConfigParser()
config.add_section("gui")
config.set("gui", "use_pymol", value="False")

config.add_section("exec")
config.set("exec", "OPTIM", value="OPTIM", )
config.set("exec", "GMIN", value="GMIN")
config.set("exec", "AMBOPTIM", value="AMBOPTIM")

print("Open option file",expanduser("~")+'/.pele/pele.ini')
config.read(expanduser("~")+'/.pele/pele.ini')

Though the build in python2.7 also conflict with munkres.py which I haven't editted.

**Comment by js850** [comment]
Thanks @WCEdison , I completed your PR.  I'll close this issue as resolved.
